### PR TITLE
add docs

### PR DESCRIPTION
**Pull request by codesalley**
add erb file outlining the structure of the database and the relationships between models. 

# new
reorganize the models and redirect where arrows should point to.

### CODE REVIEW

**Review by lekegitrepo — CHANGES_REQUESTED** [review]
## Status: Changes Required! :recycle:
### Hi @juxsalley :clap: :clap:
#### Good job :+1:
#### However, some requirements are missing. Check my comments below :point_down:

#### 1) Live Demo Link:
 - The Heroku live demo link is missing.

#### 2) Merge to main branch:
 - At this stage of development you are expected to merge everything you have done so far to the main/master branch.

#### _Reviewed by Temitayo Adeleke_

**Review by oloomoses — CHANGES_REQUESTED** [review]
## Changes Required.
**Hello @juxsalley, there seems to be a lot of confusion on this project based on the previous review feedback. None the less, this is a great start, your ERD is impressive :clap:
Check out some of the issues to fix :point_down:**

- [ ] Make sure that Primary Keys (PK) and Foreign Keys (FK) are assigned correctly
- [ ] Ensure that the Friendship table has `status` or `confirmed` column
- [ ] Kindly add the like entity in your erd model
- [ ] The User table should have an `image_link` column
- [ ] Show mutual friendship relationship between the User and Friendship table

Kindly implement the above changes before submitting another code review.
### If you have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help
## HAPPY CODING 
_Slack: Oloo Moses_

**Comment by descholar-ceo** [comment]
# This Pull Request is under review by [descholar-ceo](https://github.com/descholar-ceo) :eyes: :eyes: 
## Please wait a bit ...

**Review by descholar-ceo — CHANGES_REQUESTED** [review]
# Status: Changes Required :vertical_traffic_light: :warning: 
## Hello @juxsalley  :handshake: :handshake: :handshake: 

:+1: I liked that you have tried to implemented the requested changes from the previous review, keep it up, and your project is really almost done.
#### :warning: However we need to make few changes to mark this project approved, don't feel discouraged because of being asked some changes more and more, that's because this is a learning process, and we are here to help you to become an out-standing developer. See the requested change below :point_down: :point_down: :point_down: 
### Note: All of requested changes which are marked as [Required] are mandatory to be implemented in order to get this project approved, others which are marked as [Optional] are nice to have in your project to make it outstanding

# [Required Changes] :red_circle: 
### Friendship and user table
- [x] Great on adding friendship entity to your ERD, but there is still some requirements missing about it. Because a friend of a given user is coming from the same table users, then that relationship will be considered as a `many-to-many` relationship between table users and itself, in that case you will need what we call a junction table between table user and itself to help you implement a many-to-many relationship, that's why you need table `frienship` => this will be considered as that junction table. I highly recommend you to read [this article](https://support.airtable.com/hc/en-us/articles/218734758-Airtable-s-guide-to-many-to-many-relationships#manytomany) to learn more about the many to many relationship with junction table.

:point_right: After you understand well how to implement a many to many relationship, then change the association between friendship and user tables accordingly.

### user and post
- [x] Think again about user and post, actualy in reality `one user should have many posts` and one `post belongs to only one user` no post can belongs to more than one user. Please based on that fact, change the two relationships between table user and post accordingly

### user and likes
- [x] As a matter of fact, it's not one like which belongs to many users, I think you did the inverse. It should be `one user has many likes`, and `one like belongs to only one user`

### likes and post
- [x] The same thing applies to the association between likes and post, it's not one like which belongs to many post, it should be one post which has many likes 
___
_If anything seems to be unclear to you, reachout and ask anything by commenting on this Pull Request and mention me as [descholar-ceo](https://github.com/descholar-ceo), I will receive a notification and will respond._

[GitHub](https://github.com/descholar-ceo) | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

_Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)_

**Review by rindrajosia — CHANGES_REQUESTED** [review]
Changes Required :red_circle:
To Highlight: :angel:

- Good progress :+1:

To Improve :factory_worker:
 

- [ ] Let's see together how your ERD should look:

friendship


userandothers

postandother

- [x] It will be nice if you add Primary keys in each table.

Repo:

- [x] Please add `.DS_Store` in your `gitignore` file as it is not releated to your project.

That's it, you can submit another code review request after making these changes :recycle: :innocent:
With all my respect :pray:
Rindra Josia

**Review by mke2111 — CHANGES_REQUESTED** [review]
# **STATUS: CHANGES REQUIRED 🔴 ⚠️** 

## Hey Happy Coders, 👋🏽 
 **Thank you for the good job you got going on and implementing all the requested changes.**

## REQUIRED CHANGES

I'll explain this main part (RELATION between ONE and HAS MANY) so that you understand the big difference that exists between these tables.  Imagine Facebook users for my example.

- [x] One user can have many friends, posts, comments and likes.
- in your diagram, one like has many users and it should be the other way around.
- also, one comment has many users and it should be the other way around.
> Still, as previously suggested, one user should have many friendships, change the association between users table and friendship table to match the above changes

- [x] One post can have many likes and comments
- In your diagram, one like has many posts, alternate this as well.
- Also, one comment has many posts, do the same thing and alternate.

CHANGE THE ARROW SYMBOLS TO MATCH THE EXPECTED ASSOCIATION.

**Kindly make all the requested changes and submit another CRR. 👍🏽** 

## Cheers!! 🍹 & Happy Coding.

### For more inquiries, mention me [@mke2111](https://github.com/mke2111) in this PR and I'll be glad to help.

### Ping me on slack for a  🆘  **Roy Mukuye**

**Review by descholar-ceo — APPROVED** [review]
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:  
## :clap: :clap: :clap: Congratulations @Team members , your project is approved :tada: :tada: :tada: 
You have implemented all minimum requirements for this project to mark it as complete, it doesn't need more changes, you can go ahead and merge all of the changes on base branch,

Don't forget to fill the mandatory project completion form, and see you to next project,

Happy coding :computer: :computer: :computer: 

Re-reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)

**Pull request merged**
